### ISSUE TITLE
can you set colours globally?

### ISSUE THREAD

**Issue by SDenman** [gluons/vue-radio-toggle-buttons#3]
Hi,
Really like this and am using it quite a bit throughout an app I'm developing.
But since I want the same style to be consistent throughout, I was wondering if it's possible to set the colours globally rather than having to pass them each time.
Something like:
`Vue.use(VueRadioToggleButtons, {
    color:'#ff5500',
    textColor:'#000',
    selectedTextColor:'#fff'
});`
Not a big deal, but would just be neater.
Thanks
Simon.

**Comment by gluons** [comment]
Plugin options has been released on v0.1.0.

Happy New Year 2020. 🎆

**Comment by SDenman** [comment]
Many thanks!

Happy New Year to you too!

Simon
